# Generated by Django 5.0.1 on 2024-01-12 14:52

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccount_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='preferred_currency',
            field=djmoney.models.fields.CurrencyField(default='NGN', max_length=3),
        ),
    ]
