# Generated by Django 5.0.1 on 2024-01-06 19:41

import django_utz.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('grocery', 'Grocery'), ('pharmacy', 'Pharmacy'), ('restaurant', 'Restaurant'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('gift', 'Gift'), ('other', 'Other')], default='other', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(django_utz.models.mixins.UTZModelMixin, models.Model),
        ),
    ]
