# Generated by Django 5.0.1 on 2024-01-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
    ]
