# Generated by Django 5.0.1 on 2024-01-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('medical', 'Medical'), ('market', 'Market'), ('mart', 'Mart'), ('mall', 'Mall'), ('provision', 'Provision'), ('pharmacy', 'Pharmacy'), ('restaurant', 'Restaurant'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('auto', 'Auto'), ('gift', 'Gift'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
