# Generated by Django 5.0.1 on 2024-01-12 14:33

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='default_currency',
            field=djmoney.models.fields.CurrencyField(default='NGN', max_length=3),
        ),
    ]
