# Generated by Django 5.0.1 on 2024-01-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_options_store_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='signature',
            field=models.CharField(blank=True, default='917dcdd251a643c19ec1e3a0e103a709', editable=False, help_text='A unique string that identifies this store apart from its primary key. It is used in store access authorization.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='passkey',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True),
        ),
    ]
