# Generated by Django 5.0.1 on 2024-01-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_signature_alter_store_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='signature',
            field=models.CharField(blank=True, default='7169e58c4e12405fa14cc418bc5247ab', editable=False, help_text='A unique string that identifies this store apart from its primary key. It is used in store access authorization.', max_length=50, null=True),
        ),
    ]
