# Generated by Django 5.0.1 on 2024-01-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_slug_alter_store_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='signature',
            field=models.CharField(blank=True, default='b6b7f5f6f68647f198f6e9a9ee2c5efb', editable=False, help_text='A unique string that identifies this store apart from its primary key. It is used in store access authorization.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
