# Generated by Django 5.0.1 on 2024-01-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_store_signature_alter_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='signature',
            field=models.CharField(blank=True, default='4f97f0c5593342d4918d8ca69720d5cd', editable=False, help_text='A unique string that identifies this store apart from its primary key. It is used in store access authorization.', max_length=50, null=True),
        ),
    ]
