# Generated by Django 5.0.1 on 2024-01-30 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_store_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='signature',
            field=models.CharField(blank=True, default='426994d4744d473091358ac3f264bb62', editable=False, help_text='A unique string that identifies this store apart from its primary key. It is used in store access authorization.', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('name', 'owner')},
        ),
    ]
