# Generated by Django 5.0.1 on 2024-01-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_alter_store_signature_alter_store_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='signature',
            field=models.CharField(blank=True, default='efe32ba3604b48f6bb2dd57b3c5af8be', editable=False, help_text='A unique string that identifies this store apart from its primary key. It is used in store access authorization.', max_length=50, null=True),
        ),
    ]
