# Generated by Django 5.0.1 on 2024-01-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_store_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='signature',
            field=models.CharField(blank=True, default='18f4073d198d441793008e055a281fa0', editable=False, help_text='A unique string that identifies this store apart from its primary key. It is used in store access authorization.', max_length=50, null=True),
        ),
    ]
