# Generated by Django 5.0.1 on 2024-01-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-made_at',), 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
