# Generated by Django 5.0.1 on 2024-01-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('food', 'Food'), ('beauty', 'Beauty'), ('health', 'Health'), ('home', 'Home'), ('books', 'Books'), ('sports', 'Sports'), ('automobile', 'Automobile'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
