# Generated by Django 5.0.1 on 2024-01-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'ordering': ['name'], 'verbose_name': 'Product Brand', 'verbose_name_plural': 'Product Brands'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
    ]
