# Generated by Django 5.0.1 on 2024-01-29 20:27

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_alter_productbrand_options_and_more'),
        ('stores', '0009_alter_store_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', '-added_at'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'ordering': ('name', '-created_at'), 'verbose_name': 'Product Brand', 'verbose_name_plural': 'Product Brands'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ('name', '-created_at'), 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), default_currency='NGN', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.00'))]),
        ),
        migrations.AlterUniqueTogether(
            name='productbrand',
            unique_together={('name', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='productgroup',
            unique_together={('name', 'store')},
        ),
    ]
